# Generated by Django 5.1.5 on 2025-01-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Derector',
            new_name='Director',
        ),
    ]
