# Generated by Django 5.1.5 on 2025-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.ImageField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), ('4', 4), ('5', 5)], null=True, upload_to=''),
        ),
    ]
